name: Generate podcast feed

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run feed generator
        uses: frankAksenia/podcast-generator@main

    
